---
AWSTemplateFormatVersion: 2010-09-09


Parameters:
  VpcId:
    Type: String

  ContextPath:
    Type: String

  LoadBalancerListenerArn:
    Type: String

  LoadBalancerListenerRulePriority:
    Type: Number


Resources:
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref VpcId
      Port: 8080
      Protocol: HTTP
      Matcher:
        HttpCode: 200-299
      HealthCheckIntervalSeconds: 100
      HealthCheckPath: !Sub "${ContextPath}/healthcheck/"
      HealthCheckProtocol: HTTP
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      TargetType: instance
      TargetGroupAttributes:
        - Key: deregistration_delay.timeout_seconds
          Value: 1000

  ListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref LoadBalancerListenerArn
      Priority: !Ref LoadBalancerListenerRulePriority
      Conditions:
        - Field: path-pattern
          Values:
            - !Sub "${ContextPath}/*"
      Actions:
        - TargetGroupArn: !Ref TargetGroup
          Type: forward


Outputs:
  TargetGroup:
    Value: !Ref TargetGroup